# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      singlestore:
        image: memsql/cluster-in-a-box
        ports:
          - 3306:3306
          - 8080:8080
        volumes:
          # persist data between runs:
          - db-data:/var/lib/memsql
          - /home/user/init.sql:/init.sql
        env:
          # use the LICENSE_KEY environment variable set in the terminal:
          LICENSE_KEY: ${SINGLESTORE_LICENSE}
          ROOT_PASSWORD: helloworld
          START_AFTER_INIT: Y
    steps:
      - uses: actions/checkout@v3
      - name: Create env
        run: |
          mkdir config && echo "${{ secrets.ENV_FILE }}" > config/config.env && echo "${{ secrets.FIREBASE_ADMIN }}" > config/ownify-wallet-service-account.json
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Test
        run: go test -v ./...
